# Employee Attrition Analytics

## Module 1: Dataset Creation

### Objective
Create a realistic synthetic employee dataset that will be used throughout this project for data cleaning, exploratory data analysis, feature engineering, machine learning, and dashboard creation.

In [54]:
import pandas as pd
import numpy as np
from faker import Faker
import random

## Initialize Faker and Set Random Seeds

Setting random seeds ensures the dataset is reproducible. Every time this notebook is executed, the same dataset will be generated.

In [55]:
fake = Faker()

random.seed(42)
np.random.seed(42)
Faker.seed(42)

## Define Dataset Categories

Define all categorical values in one place to make the dataset easier to maintain and update.

In [56]:
departments = ["IT", "HR", "Finance", "Sales", "Marketing"]

job_roles = {
    "IT": ["Software Engineer", "Data Analyst", "DevOps Engineer"],
    "HR": ["HR Executive", "Recruiter"],
    "Finance": ["Accountant", "Financial Analyst"],
    "Sales": ["Sales Executive", "Sales Manager"],
    "Marketing": ["Marketing Specialist", "SEO Executive"],
}

education_levels = ["Bachelor", "Master", "PhD"]

cities = ["Karachi", "Lahore", "Islamabad", "Rawalpindi", "Faisalabad", "Peshawar"]

employment_types = ["Full-Time", "Contract"]

## Verify Categories

Display the available categories before generating the dataset.

In [57]:
print("Departments:")
print(departments)

print("\nEducation Levels:")
print(education_levels)

print("\nCities:")
print(cities)

Departments:
['IT', 'HR', 'Finance', 'Sales', 'Marketing']

Education Levels:
['Bachelor', 'Master', 'PhD']

Cities:
['Karachi', 'Lahore', 'Islamabad', 'Rawalpindi', 'Faisalabad', 'Peshawar']

## Create an Empty List

Each generated employee record will be stored as a dictionary inside a list. Later, the list will be converted into a Pandas DataFrame.

In [58]:
employees = []

print(type(employees))

<class 'list'>

## Define Data Generation Rules

To make the dataset realistic, several columns will have logical relationships. For example, salary will depend on experience, and job satisfaction will influence attrition.

In [59]:
salary_rules = {
    "0-2": (40000, 70000),
    "3-5": (70000, 100000),
    "6-10": (100000, 150000),
    "10+": (150000, 250000),
}

project_rules = {"0-2": (1, 3), "3-5": (3, 6), "6-10": (6, 10), "10+": (8, 15)}

print("Salary Rules")
print(salary_rules)

print("\nProject Rules")
print(project_rules)

Salary Rules
{'0-2': (40000, 70000), '3-5': (70000, 100000), '6-10': (100000, 150000), '10+': (150000, 250000)}

Project Rules
{'0-2': (1, 3), '3-5': (3, 6), '6-10': (6, 10), '10+': (8, 15)}

## Generate Employee Records

Generate 1,000 realistic employee records using predefined business rules and store them in a list.

In [69]:
employees = []

for employee_id in range(1, 1001):

    # Basic Information
    department = random.choice(departments)
    role = random.choice(job_roles[department])

    age = random.randint(22, 60)
    gender = random.choice(["Male", "Female"])
    experience = random.randint(0, age - 21)

    education = random.choice(education_levels)
    city = random.choice(cities)
    employment = random.choice(employment_types)

    # Salary and Projects
    if experience <= 2:
        salary = random.randint(40000, 70000)
        projects = random.randint(1, 3)

    elif experience <= 5:
        salary = random.randint(70000, 100000)
        projects = random.randint(3, 6)

    elif experience <= 10:
        salary = random.randint(100000, 150000)
        projects = random.randint(6, 10)

    else:
        salary = random.randint(150000, 250000)
        projects = random.randint(8, 15)

    # Performance
    performance = random.randint(1, 5)
    manager_rating = random.randint(4, 10)

    work_hours = random.randint(35, 55)

    overtime = random.choice(["Yes", "No"])
    remote_work = random.choice(["Yes", "No"])

    training_hours = random.randint(5, 80)

    sick_leaves = random.randint(0, 15)

    # Job Satisfaction
    if overtime == "Yes":
        job_satisfaction = random.randint(3, 8)
    else:
        job_satisfaction = random.randint(6, 10)

    # Promotion
    if performance >= 4:
        promotion = random.choice(["Yes", "No"])
    else:
        promotion = "No"

    # Attrition
    if job_satisfaction <= 4:
        attrition = random.choice(["Yes", "Yes", "No"])
    else:
        attrition = "No"

    # Joining Date
    joining_date = fake.date_between(
        start_date="-15y",
        end_date="today"
    )

    # Employee Record
    employee = {
        "Employee_ID": employee_id,
        "Age": age,
        "Gender": gender,
        "Department": department,
        "Job_Role": role,
        "Experience": experience,
        "Education": education,
        "Salary": salary,
        "Performance_Score": performance,
        "Job_Satisfaction": job_satisfaction,
        "Overtime": overtime,
        "Work_Hours": work_hours,
        "Remote_Work": remote_work,
        "Training_Hours": training_hours,
        "Projects": projects,
        "Promotion_Last_5Yrs": promotion,
        "Joining_Date": joining_date,
        "Attrition": attrition,
        "City": city,
        "Employment_Type": employment,
        "Manager_Rating": manager_rating,
        "Sick_Leaves": sick_leaves
    }

    employees.append(employee)

print(f"Total Employees Generated: {len(employees)}")

Total Employees Generated: 1000

## Create DataFrame

In [70]:
df = pd.DataFrame(employees)

df.head()

,Employee_ID,Age,Gender,Department,Job_Role,Experience,Education,Salary,Performance_Score,Job_Satisfaction,...,Remote_Work,Training_Hours,Projects,Promotion_Last_5Yrs,Joining_Date,Attrition,City,Employment_Type,Manager_Rating,Sick_Leaves
0,1,40,Male,Sales,Sales Manager,3,Master,94113,5,6,...,No,70,5,No,2011-12-21,No,Rawalpindi,Contract,5,6
1,2,39,Female,Sales,Sales Manager,2,Master,54224,4,9,...,No,33,3,Yes,2015-09-20,No,Islamabad,Full-Time,4,4
2,3,49,Male,Finance,Financial Analyst,25,Master,166749,2,6,...,Yes,75,12,No,2014-12-10,No,Islamabad,Full-Time,8,2
3,4,54,Female,Marketing,Marketing Specialist,26,Bachelor,196590,5,4,...,Yes,64,12,No,2022-08-23,Yes,Rawalpindi,Contract,4,5
4,5,41,Female,IT,Data Analyst,18,PhD,231764,3,8,...,Yes,15,12,No,2021-09-29,No,Rawalpindi,Contract,10,8

## Check Dataset Information

In [71]:
print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

Dataset Shape: (1000, 22)

Column Names:
Index(['Employee_ID', 'Age', 'Gender', 'Department', 'Job_Role', 'Experience',
       'Education', 'Salary', 'Performance_Score', 'Job_Satisfaction',
       'Overtime', 'Work_Hours', 'Remote_Work', 'Training_Hours', 'Projects',
       'Promotion_Last_5Yrs', 'Joining_Date', 'Attrition', 'City',
       'Employment_Type', 'Manager_Rating', 'Sick_Leaves'],
      dtype='str')

Data Types:
Employee_ID             int64
Age                     int64
Gender                    str
Department                str
Job_Role                  str
Experience              int64
Education                 str
Salary                  int64
Performance_Score       int64
Job_Satisfaction        int64
Overtime                  str
Work_Hours              int64
Remote_Work               str
Training_Hours          int64
Projects                int64
Promotion_Last_5Yrs       str
Joining_Date           object
Attrition                 str
City                      str
Employment_Type           str
Manager_Rating          int64
Sick_Leaves             int64
dtype: object

## Save Dataset

In [72]:
df.to_csv("../data/raw/employee_hr_analytics.csv", index=False)

print("Dataset saved successfully.")

Dataset saved successfully.

## Verify Saved Dataset

In [73]:
saved_df = pd.read_csv("../data/raw/employee_hr_analytics.csv")

saved_df.head()

,Employee_ID,Age,Gender,Department,Job_Role,Experience,Education,Salary,Performance_Score,Job_Satisfaction,...,Remote_Work,Training_Hours,Projects,Promotion_Last_5Yrs,Joining_Date,Attrition,City,Employment_Type,Manager_Rating,Sick_Leaves
0,1,40,Male,Sales,Sales Manager,3,Master,94113,5,6,...,No,70,5,No,2011-12-21,No,Rawalpindi,Contract,5,6
1,2,39,Female,Sales,Sales Manager,2,Master,54224,4,9,...,No,33,3,Yes,2015-09-20,No,Islamabad,Full-Time,4,4
2,3,49,Male,Finance,Financial Analyst,25,Master,166749,2,6,...,Yes,75,12,No,2014-12-10,No,Islamabad,Full-Time,8,2
3,4,54,Female,Marketing,Marketing Specialist,26,Bachelor,196590,5,4,...,Yes,64,12,No,2022-08-23,Yes,Rawalpindi,Contract,4,5
4,5,41,Female,IT,Data Analyst,18,PhD,231764,3,8,...,Yes,15,12,No,2021-09-29,No,Rawalpindi,Contract,10,8