# Employee Attrition Analytics

## Module 3: Data Cleaning

### Objective
Clean and validate the employee dataset by handling missing values, duplicates, inconsistent categories, invalid values, and outliers.

In [1]:
import pandas as pd
import numpy as np

## Load Dirty Dataset

In [2]:
df = pd.read_csv("../data/raw/employee_hr_analytics_dirty.csv")

df.head()

,Employee_ID,Age,Gender,Department,Job_Role,Experience,Education,Salary,Performance_Score,Job_Satisfaction,...,Remote_Work,Training_Hours,Projects,Promotion_Last_5Yrs,Joining_Date,Attrition,City,Employment_Type,Manager_Rating,Sick_Leaves
0,1,40.0,Male,Sales,Sales Manager,3,Master,94113.0,5,6.0,...,No,70,5,No,2011-12-21,No,Rawalpindi,Contract,5,6
1,2,39.0,Female,Sales,Sales Manager,2,Master,54224.0,4,9.0,...,No,33,3,Yes,2015-09-20,No,Islamabad,Full-Time,4,4
2,3,49.0,Male,finance,Financial Analyst,25,Master,166749.0,2,6.0,...,Yes,75,12,No,2014-12-10,No,Islamabad,Full-Time,8,2
3,4,54.0,Female,MARKETING,Marketing Specialist,26,Bachelor,196590.0,5,4.0,...,Yes,64,12,No,2022-08-23,Yes,Rawalpindi,Contract,4,5
4,5,41.0,Female,I.T,Data Analyst,18,PhD,231764.0,3,8.0,...,Yes,15,12,No,2021-09-29,No,Rawalpindi,Contract,10,8

## Inspect Dataset Structure

In [3]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

Number of rows: 1010
Number of columns: 22

Column names:
['Employee_ID', 'Age', 'Gender', 'Department', 'Job_Role', 'Experience', 'Education', 'Salary', 'Performance_Score', 'Job_Satisfaction', 'Overtime', 'Work_Hours', 'Remote_Work', 'Training_Hours', 'Projects', 'Promotion_Last_5Yrs', 'Joining_Date', 'Attrition', 'City', 'Employment_Type', 'Manager_Rating', 'Sick_Leaves']

Data types:
Employee_ID              int64
Age                    float64
Gender                     str
Department                 str
Job_Role                   str
Experience               int64
Education                  str
Salary                 float64
Performance_Score        int64
Job_Satisfaction       float64
Overtime                   str
Work_Hours               int64
Remote_Work                str
Training_Hours           int64
Projects                 int64
Promotion_Last_5Yrs        str
Joining_Date               str
Attrition                  str
City                       str
Employment_Type            str
Manager_Rating           int64
Sick_Leaves              int64
dtype: object

## Dataset Information

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          1010 non-null   int64
 1   Age                  980 non-null    float64
 2   Gender               1010 non-null   str
 3   Department           990 non-null    str
 4   Job_Role             1010 non-null   str
 5   Experience           1010 non-null   int64
 6   Education            1010 non-null   str
 7   Salary               990 non-null    float64
 8   Performance_Score    1010 non-null   int64
 9   Job_Satisfaction     990 non-null    float64
 10  Overtime             1010 non-null   str
 11  Work_Hours           1010 non-null   int64
 12  Remote_Work          1010 non-null   str
 13  Training_Hours       1010 non-null   int64
 14  Projects             1010 non-null   int64
 15  Promotion_Last_5Yrs  1010 non-null   str
 16  Joining_Date         1010 non-null   str
 17  Attrition            1010 non-null   str
 18  City                 1010 non-null   str
 19  Employment_Type      1010 non-null   str
 20  Manager_Rating       1010 non-null   int64
 21  Sick_Leaves          1010 non-null   int64
dtypes: float64(3), int64(8), str(11)
memory usage: 173.7 KB

## Summary Statistics

In [5]:
df.describe()

,Employee_ID,Age,Experience,Salary,Performance_Score,Job_Satisfaction,Work_Hours,Training_Hours,Projects,Manager_Rating,Sick_Leaves
count,1010.000000,980.000000,1010.000000,9.900000e+02,1010.000000,990.000000,1010.000000,1010.000000,1010.000000,1010.000000,1010.000000
mean,501.377228,40.413265,9.823762,1.354692e+05,2.993069,6.735354,44.783168,41.872277,7.173267,7.018812,7.443564
std,288.171491,11.948289,8.987417,1.902871e+05,1.413145,1.988507,6.103786,22.421685,4.239215,2.038442,4.512210
min,1.000000,5.000000,0.000000,-5.000000e+04,1.000000,3.000000,35.000000,5.000000,1.000000,4.000000,0.000000
25%,252.250000,30.000000,2.000000,6.926450e+04,2.000000,5.000000,40.000000,21.250000,3.000000,5.000000,4.000000
50%,503.500000,40.000000,7.000000,1.191975e+05,3.000000,7.000000,44.000000,41.000000,7.000000,7.000000,7.000000
75%,748.750000,50.000000,15.000000,1.832525e+05,4.000000,8.000000,50.000000,61.000000,11.000000,9.000000,11.000000
max,1000.000000,150.000000,38.000000,5.000000e+06,5.000000,10.000000,55.000000,80.000000,15.000000,10.000000,15.000000

## Analyze Missing Values

In [6]:
missing_count = df.isnull().sum()

missing_count

Employee_ID             0
Age                    30
Gender                  0
Department             20
Job_Role                0
Experience              0
Education               0
Salary                 20
Performance_Score       0
Job_Satisfaction       20
Overtime                0
Work_Hours              0
Remote_Work             0
Training_Hours          0
Projects                0
Promotion_Last_5Yrs     0
Joining_Date            0
Attrition               0
City                    0
Employment_Type         0
Manager_Rating          0
Sick_Leaves             0
dtype: int64

## Missing Value Percentage

In [7]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage = missing_percentage.round(2)

missing_percentage[missing_percentage > 0]

Age                 2.97
Department          1.98
Salary              1.98
Job_Satisfaction    1.98
dtype: float64

## Handle Missing Values

In [8]:
df["Age"] = df["Age"].fillna(df["Age"].median())

df["Salary"] = df["Salary"].fillna(df["Salary"].median())

df["Job_Satisfaction"] = df["Job_Satisfaction"].fillna(df["Job_Satisfaction"].median())

df["Department"] = df["Department"].fillna(df["Department"].mode()[0])

## Verify Missing Values

In [9]:
df.isnull().sum()

Employee_ID            0
Age                    0
Gender                 0
Department             0
Job_Role               0
Experience             0
Education              0
Salary                 0
Performance_Score      0
Job_Satisfaction       0
Overtime               0
Work_Hours             0
Remote_Work            0
Training_Hours         0
Projects               0
Promotion_Last_5Yrs    0
Joining_Date           0
Attrition              0
City                   0
Employment_Type        0
Manager_Rating         0
Sick_Leaves            0
dtype: int64

## Detect Duplicate Records

In [10]:
duplicate_count = df.duplicated().sum()

print("Duplicated rows:", duplicate_count)

Duplicated rows: 10

## Remove Duplicate Records

In [11]:
df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (1000, 22)

## Verify Duplicates

In [12]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

## Convert Joining Date to Datetime

In [13]:
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])

df["Joining_Date"].dtype

dtype('<M8[us]')

## Remove Extra Spaces

In [14]:
df["City"] = df["City"].str.strip()

## Verify City Values

In [15]:
df["City"].unique()

<StringArray>
['Rawalpindi', 'Islamabad', 'Karachi', 'Peshawar', 'Lahore', 'Faisalabad']
Length: 6, dtype: str

## Standardize Department Names

In [16]:
department_mapping = {
    "I.T": "IT",
    "Human Resource": "HR",
    "finance": "Finance",
    "MARKETING": "Marketing",
}

df["Department"] = df["Department"].replace(department_mapping)

## Verify Department Categories

In [17]:
df["Department"].value_counts()

Department
HR           229
Sales        199
Marketing    196
Finance      194
IT           182
Name: count, dtype: int64

## Detect Invalid Ages

In [18]:
invalid_age = df[(df["Age"] < 18) | (df["Age"] > 65)]

invalid_age[["Employee_ID", "Age"]]

    Employee_ID    Age
5             6  150.0
12           13    5.0

## Correct Invalid Ages

In [19]:
median_age = df.loc[(df["Age"] >= 18) & (df["Age"] <= 65), "Age"].median()

df.loc[(df["Age"] < 18) | (df["Age"] > 65), "Age"] = median_age

## Verify Age Range

In [20]:
print("Minimum age:", df["Age"].min())
print("Maximum age:", df["Age"].max())

Minimum age: 22.0
Maximum age: 60.0

## Detect Invalid Salaries

In [21]:
invalid_salary = df[df["Salary"] <= 0]

invalid_salary[["Employee_ID", "Salary"]]

   Employee_ID   Salary
8            9 -50000.0

## Correct Invalid Salaries

In [22]:
valid_salary_median = df.loc[
    df["Salary"] > 0,
    "Salary",
].median()

df.loc[df["Salary"] <= 0, "Salary"] = valid_salary_median

## Verify Salary Values

In [23]:
print("Minimun salary:", df["Salary"].min())
print("Maximum slary:", df["Salary"].max())

Minimun salary: 40039.0
Maximum slary: 5000000.0

## Detect Salary Outliers Using IQR

In [24]:
Q1 = df["Salary"].quantile(0.25)
Q3 = df["Salary"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3", Q3)
print("IQR", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

Q1: 69628.5
Q3 182615.25
IQR 112986.75
Lower bound: -99851.625
Upper bound: 352095.375

## Count Salary Outliers

In [25]:
salary_outliers = df[(df["Salary"] < lower_bound) | (df["Salary"] > upper_bound)]
print("Number of salary outliers:", len(salary_outliers))

Number of salary outliers: 2

## Inspect Salary Outliers

In [26]:
salary_outliers[
    ["Employee_ID", "Experience", "Department", "Job_Role", "Salary"]
].sort_values("Salary", ascending=False)

    Employee_ID  Experience Department           Job_Role     Salary
30           31           8    Finance         Accountant  5000000.0
55           56          32         IT  Software Engineer  3000000.0

## Cap Salary Outliers

In [27]:
df["Salary"] = df["Salary"].clip(lower=lower_bound, upper=upper_bound)

## Verify Salary Outliers

In [28]:
print("Minimum salary:", df["Salary"].min())
print("Maximum salary:", df["Salary"].max())

remaining_outliers = df[(df["Salary"] < lower_bound) | (df["Salary"] > upper_bound)]

print("Remaining outiers:", len(remaining_outliers))

Minimum salary: 40039.0
Maximum salary: 352095.375
Remaining outiers: 0

## Final Data Quality Check

In [30]:
print("Dataset shape")
print(df.shape)

print("\nMissing values:")
print(df.isnull().sum().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nMinimum age:")
print(df["Age"].min())

print("\nMaximum age:")
print(df["Age"].max())

print("\nMinimum salary:")
print(df["Salary"].min())

print("\nDepartment Categories:")
print(df["Department"].unique())

Dataset shape
(1000, 22)

Missing values:
0

Duplicate rows:
0

Minimum age:
22.0

Maximum age:
60.0

Minimum salary:
40039.0

Department Categories:
<StringArray>
['Sales', 'Finance', 'Marketing', 'IT', 'HR']
Length: 5, dtype: str

## Save Clean Dataset

In [ ]:
output_path = "../data/processed/employee_hr_analytics_clean.csv"
df.to_csv(output_path, index=False)
print(f"Clean dataset saved to:{output_path}")

Clean dataset saved to:../data/processed/employee_r_analytics_clean.csv

## Verify Saved Dataset

In [32]:
clean_df = pd.read_csv(output_path)
print("Shape:", clean_df.shape)

print("\nMissing values:", clean_df.isnull().sum().sum())

print("\nDuplicate rows:", clean_df.duplicated().sum())

clean_df.head()

Shape: (1000, 22)

Missing values: 0

Duplicate rows: 0

,Employee_ID,Age,Gender,Department,Job_Role,Experience,Education,Salary,Performance_Score,Job_Satisfaction,...,Remote_Work,Training_Hours,Projects,Promotion_Last_5Yrs,Joining_Date,Attrition,City,Employment_Type,Manager_Rating,Sick_Leaves
0,1,40.0,Male,Sales,Sales Manager,3,Master,94113.0,5,6.0,...,No,70,5,No,2011-12-21,No,Rawalpindi,Contract,5,6
1,2,39.0,Female,Sales,Sales Manager,2,Master,54224.0,4,9.0,...,No,33,3,Yes,2015-09-20,No,Islamabad,Full-Time,4,4
2,3,49.0,Male,Finance,Financial Analyst,25,Master,166749.0,2,6.0,...,Yes,75,12,No,2014-12-10,No,Islamabad,Full-Time,8,2
3,4,54.0,Female,Marketing,Marketing Specialist,26,Bachelor,196590.0,5,4.0,...,Yes,64,12,No,2022-08-23,Yes,Rawalpindi,Contract,4,5
4,5,41.0,Female,IT,Data Analyst,18,PhD,231764.0,3,8.0,...,Yes,15,12,No,2021-09-29,No,Rawalpindi,Contract,10,8