# SQL Analysis

In this module, we will use SQL to analyze the cleaned employee dataset.

The employee data will be loaded into a SQLite database and analyzed using SQL queries.

In [1]:
import pandas as pd
import sqlite3

## Load the Cleaned Employee Dataset

We will use the cleaned HR dataset created during the data cleaning stage.

In [ ]:
df = pd.read_csv("../data/processed/employee_hr_analytics_clean.csv")

df.head()

,Employee_ID,Age,Gender,Department,Job_Role,Experience,Education,Salary,Performance_Score,Job_Satisfaction,...,Remote_Work,Training_Hours,Projects,Promotion_Last_5Yrs,Joining_Date,Attrition,City,Employment_Type,Manager_Rating,Sick_Leaves
0,1,40.0,Male,Sales,Sales Manager,3,Master,94113.0,5,6.0,...,No,70,5,No,2011-12-21,No,Rawalpindi,Contract,5,6
1,2,39.0,Female,Sales,Sales Manager,2,Master,54224.0,4,9.0,...,No,33,3,Yes,2015-09-20,No,Islamabad,Full-Time,4,4
2,3,49.0,Male,Finance,Financial Analyst,25,Master,166749.0,2,6.0,...,Yes,75,12,No,2014-12-10,No,Islamabad,Full-Time,8,2
3,4,54.0,Female,Marketing,Marketing Specialist,26,Bachelor,196590.0,5,4.0,...,Yes,64,12,No,2022-08-23,Yes,Rawalpindi,Contract,4,5
4,5,41.0,Female,IT,Data Analyst,18,PhD,231764.0,3,8.0,...,Yes,15,12,No,2021-09-29,No,Rawalpindi,Contract,10,8

In [12]:
print("Dataset Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

Dataset Shape: (1000, 22)

Columns:
['Employee_ID', 'Age', 'Gender', 'Department', 'Job_Role', 'Experience', 'Education', 'Salary', 'Performance_Score', 'Job_Satisfaction', 'Overtime', 'Work_Hours', 'Remote_Work', 'Training_Hours', 'Projects', 'Promotion_Last_5Yrs', 'Joining_Date', 'Attrition', 'City', 'Employment_Type', 'Manager_Rating', 'Sick_Leaves']

## Check the Dataset

In [3]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1000
Columns: 22

## Create the SQLite Database

We will create a SQLite database and store the employee dataset in a table called `employees`.

In [ ]:
connection = sqlite3.connect("../data/employee_attrition.db")

print("SQLite database connected successfully.")

SQLite database connected successfully.

In [14]:
df.to_sql("employees", connection, if_exists="replace", index=False)

print("Employee data loaded into SQL table successfully.")

Employee data loaded into SQL table successfully.

## Verify the SQL Table

Before performing analysis, we will verify that the employee table was created correctly.

In [ ]:
query = """
SELECT *
FROM employees
LIMIT 5;
"""

result = pd.read_sql_query(query, connection)

result

,Employee_ID,Age,Gender,Department,Job_Role,Experience,Education,Salary,Performance_Score,Job_Satisfaction,...,Remote_Work,Training_Hours,Projects,Promotion_Last_5Yrs,Joining_Date,Attrition,City,Employment_Type,Manager_Rating,Sick_Leaves
0,1,40.0,Male,Sales,Sales Manager,3,Master,94113.0,5,6.0,...,No,70,5,No,2011-12-21,No,Rawalpindi,Contract,5,6
1,2,39.0,Female,Sales,Sales Manager,2,Master,54224.0,4,9.0,...,No,33,3,Yes,2015-09-20,No,Islamabad,Full-Time,4,4
2,3,49.0,Male,Finance,Financial Analyst,25,Master,166749.0,2,6.0,...,Yes,75,12,No,2014-12-10,No,Islamabad,Full-Time,8,2
3,4,54.0,Female,Marketing,Marketing Specialist,26,Bachelor,196590.0,5,4.0,...,Yes,64,12,No,2022-08-23,Yes,Rawalpindi,Contract,4,5
4,5,41.0,Female,IT,Data Analyst,18,PhD,231764.0,3,8.0,...,Yes,15,12,No,2021-09-29,No,Rawalpindi,Contract,10,8

## Select Specific Columns

Instead of selecting every column, we can select only the columns required for an analysis.

In [ ]:
query = """
SELECT
    Employee_ID,
    Department,
    Job_Role,
    Salary,
    Attrition
FROM employees
LIMIT 10;
"""

result = pd.read_sql_query(query, connection)

result

   Employee_ID Department              Job_Role    Salary Attrition
0            1      Sales         Sales Manager   94113.0        No
1            2      Sales         Sales Manager   54224.0        No
2            3    Finance     Financial Analyst  166749.0        No
3            4  Marketing  Marketing Specialist  196590.0       Yes
4            5         IT          Data Analyst  231764.0        No
5            6         IT          Data Analyst   45627.0        No
6            7         HR          HR Executive   68148.0       Yes
7            8      Sales       Sales Executive   64208.0        No
8            9         HR       Sales Executive  119197.5        No
9           10         HR          HR Executive  119197.5        No

## Filter Employees by Department

The `WHERE` clause allows us to filter records based on a condition.

We will retrieve employees who work in the IT department.

In [17]:
query = """
SELECT
    Employee_ID,
    Department,
    Job_Role,
    Salary,
    Attrition
FROM employees
WHERE Department = 'IT';
"""

it_employees = pd.read_sql_query(query, connection)

it_employees.head(10)

   Employee_ID Department           Job_Role    Salary Attrition
0            5         IT       Data Analyst  231764.0        No
1            6         IT       Data Analyst   45627.0        No
2           13         IT  Software Engineer  215991.0        No
3           23         IT  Software Engineer   69114.0        No
4           28         IT    DevOps Engineer  143938.0        No
5           29         IT    DevOps Engineer  224743.0        No
6           32         IT    DevOps Engineer   83527.0        No
7           36         IT       Data Analyst  140006.0        No
8           39         IT       Data Analyst   66490.0        No
9           41         IT  Software Engineer  238864.0        No

## Identify Employees Who Left

We will filter the dataset to identify employees whose attrition status is `Yes`.

In [18]:
query = """
SELECT
    Employee_ID,
    Department,
    Job_Role,
    Salary,
    Attrition
FROM employees
WHERE Attrition = 'Yes';
"""

employees_left = pd.read_sql_query(query, connection)

employees_left.head(10)

   Employee_ID Department              Job_Role    Salary Attrition
0            4  Marketing  Marketing Specialist  196590.0       Yes
1            7         HR          HR Executive   68148.0       Yes
2           15         HR          HR Executive   64968.0       Yes
3           49    Finance     Financial Analyst  157512.0       Yes
4           59      Sales       Sales Executive   81766.0       Yes
5           64      Sales       Sales Executive  224647.0       Yes
6           65         HR          HR Executive  129796.0       Yes
7           68    Finance     Financial Analyst   85002.0       Yes
8           71    Finance     Financial Analyst  119197.5       Yes
9           90  Marketing  Marketing Specialist   79068.0       Yes

## Count Employees Who Left

We will use the `COUNT()` function to calculate the total number of employees who left the organization.

In [ ]:
query = """
SELECT
    COUNT(*) AS Employees_Left
FROM employees
WHERE Attrition = 'Yes';
"""

result = pd.read_sql_query(query, connection)

result

   Employees_Left
0             118

## Count Total Employees

We will calculate the total number of employees in the dataset.

In [ ]:
query = """
SELECT
    COUNT(*) AS Total_Employees
FROM employees;
"""

result = pd.read_sql_query(query, connection)

result

   Total_Employees
0             1000

## Calculate Overall Attrition Rate

We will calculate the organization's overall employee attrition rate.

Attrition Rate = Employees Left / Total Employees × 100

In [ ]:
query = """
SELECT
    COUNT(*) AS Total_Employees,

    SUM(
        CASE
            WHEN Attrition = 'Yes' THEN 1
            ELSE 0
        END
    ) AS Employees_Left,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN Attrition = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS Attrition_Rate

FROM employees;
"""

overall_attrition = pd.read_sql_query(query, connection)

overall_attrition

   Total_Employees  Employees_Left  Attrition_Rate
0             1000             118            11.8

## Employee Distribution by Department

The `GROUP BY` clause allows us to divide employees into groups.

We will calculate the number of employees in each department.

In [22]:
query = """
SELECT
    Department,
    COUNT(*) AS Total_Employees
FROM employees
GROUP BY Department
ORDER BY Total_Employees DESC;
"""

department_employee_count = pd.read_sql_query(query, connection)

department_employee_count

  Department  Total_Employees
0         HR              229
1      Sales              199
2  Marketing              196
3    Finance              194
4         IT              182

## Attrition by Department

We will calculate the total employees and the number of employees who left for each department.

In [ ]:
query = """
SELECT
    Department,

    COUNT(*) AS Total_Employees,

    SUM(
        CASE
            WHEN Attrition = 'Yes' THEN 1
            ELSE 0
        END
    ) AS Employees_Left

FROM employees
GROUP BY Department
ORDER BY Employees_Left DESC;
"""

department_attrition = pd.read_sql_query(query, connection)

department_attrition

  Department  Total_Employees  Employees_Left
0  Marketing              196              29
1      Sales              199              25
2         HR              229              24
3         IT              182              23
4    Finance              194              17

## Attrition Rate by Department

We will calculate the attrition rate for each department.

This allows us to compare employee turnover between departments of different sizes.

In [ ]:
query = """
SELECT
    Department,

    COUNT(*) AS Total_Employees,

    SUM(
        CASE
            WHEN Attrition = 'Yes' THEN 1
            ELSE 0
        END
    ) AS Employees_Left,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN Attrition = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS Attrition_Rate

FROM employees

GROUP BY Department

ORDER BY Attrition_Rate DESC;
"""

department_attrition_rate = pd.read_sql_query(query, connection)

department_attrition_rate

  Department  Total_Employees  Employees_Left  Attrition_Rate
0  Marketing              196              29           14.80
1         IT              182              23           12.64
2      Sales              199              25           12.56
3         HR              229              24           10.48
4    Finance              194              17            8.76

## Attrition Rate by Job Role

We will calculate employee attrition for each job role to identify roles with relatively higher employee turnover.

In [ ]:
query = """
SELECT
    Job_Role,

    COUNT(*) AS Total_Employees,

    SUM(
        CASE
            WHEN Attrition = 'Yes' THEN 1
            ELSE 0
        END
    ) AS Employees_Left,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN Attrition = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS Attrition_Rate

FROM employees

GROUP BY Job_Role

ORDER BY Attrition_Rate DESC;
"""

job_role_attrition = pd.read_sql_query(query, connection)

job_role_attrition

                Job_Role  Total_Employees  Employees_Left  Attrition_Rate
0        Sales Executive              111              19           17.12
1   Marketing Specialist              104              17           16.35
2      Software Engineer               71              11           15.49
3           HR Executive              106              15           14.15
4      Financial Analyst              103              14           13.59
5          SEO Executive               97              12           12.37
6        DevOps Engineer               57               7           12.28
7           Data Analyst               58               5            8.62
8              Recruiter              105               8            7.62
9          Sales Manager               91               6            6.59
10            Accountant               97               4            4.12

## Attrition Rate by Overtime

We will compare employee attrition between employees who work overtime and those who do not.

In [ ]:
query = """
SELECT
    Overtime,

    COUNT(*) AS Total_Employees,

    SUM(
        CASE
            WHEN Attrition = 'Yes' THEN 1
            ELSE 0
        END
    ) AS Employees_Left,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN Attrition = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS Attrition_Rate

FROM employees

GROUP BY Overtime

ORDER BY Attrition_Rate DESC;
"""

overtime_attrition = pd.read_sql_query(query, connection)

overtime_attrition

  Overtime  Total_Employees  Employees_Left  Attrition_Rate
0      Yes              490             118           24.08
1       No              510               0            0.00

## Attrition Rate by Promotion History

We will compare attrition between employees who received a promotion within the last five years and employees who did not.

In [ ]:
query = """
SELECT
    Promotion_Last_5Yrs,

    COUNT(*) AS Total_Employees,

    SUM(
        CASE
            WHEN Attrition = 'Yes' THEN 1
            ELSE 0
        END
    ) AS Employees_Left,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN Attrition = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS Attrition_Rate

FROM employees

GROUP BY Promotion_Last_5Yrs

ORDER BY Attrition_Rate DESC;
"""

promotion_attrition = pd.read_sql_query(query, connection)

promotion_attrition

  Promotion_Last_5Yrs  Total_Employees  Employees_Left  Attrition_Rate
0                 Yes              206              26           12.62
1                  No              794              92           11.59

## Attrition Rate by Remote Work

We will compare employee attrition between remote and non-remote employees.

In [ ]:
query = """
SELECT
    Remote_Work,

    COUNT(*) AS Total_Employees,

    SUM(
        CASE
            WHEN Attrition = 'Yes' THEN 1
            ELSE 0
        END
    ) AS Employees_Left,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN Attrition = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS Attrition_Rate

FROM employees

GROUP BY Remote_Work

ORDER BY Attrition_Rate DESC;
"""

remote_work_attrition = pd.read_sql_query(query, connection)

remote_work_attrition

  Remote_Work  Total_Employees  Employees_Left  Attrition_Rate
0          No              499              61           12.22
1         Yes              501              57           11.38

## Save SQL Analysis Results

The major SQL analysis results will be exported to the processed data directory so they can be reused in reporting and visualization.

In [ ]:
department_attrition_rate.to_csv(
    "../data/processed/sql_department_attrition.csv", index=False
)

job_role_attrition.to_csv("../data/processed/sql_job_role_attrition.csv", index=False)

overtime_attrition.to_csv("../data/processed/sql_overtime_attrition.csv", index=False)

promotion_attrition.to_csv("../data/processed/sql_promotion_attrition.csv", index=False)

remote_work_attrition.to_csv(
    "../data/processed/sql_remote_work_attrition.csv", index=False
)

print("SQL analysis results saved successfully.")

SQL analysis results saved successfully.

## Close the Database Connection

The SQL database connection is no longer needed for this notebook session, so we will close it.

In [30]:
connection.close()

print("SQLite database connection closed.")

SQLite database connection closed.

## Average Salary by Department

Salary is an important HR metric.

We will calculate the average salary for each department to understand differences in compensation across the organization.

In [ ]:
connection = sqlite3.connect("../data/employee_attrition.db")

query = """
SELECT
    Department,
    COUNT(*) AS Total_Employees,
    ROUND(AVG(Salary), 2) AS Average_Salary,
    MIN(Salary) AS Minimum_Salary,
    MAX(Salary) AS Maximum_Salary
FROM employees
GROUP BY Department
ORDER BY Average_Salary DESC;
"""

department_salary = pd.read_sql_query(query, connection)

department_salary

  Department  Total_Employees  Average_Salary  Minimum_Salary  Maximum_Salary
0    Finance              194       133855.96         40183.0      352095.375
1  Marketing              196       128487.83         40687.0      249211.000
2         IT              182       128005.05         40039.0      352095.375
3         HR              229       127708.98         40486.0      249404.000
4      Sales              199       121986.39         40104.0      240518.000

## Average Salary by Attrition Status

We will compare the average salary of employees who stayed with the organization against employees who left.

This helps us investigate whether compensation is associated with employee attrition.

In [ ]:
query = """
SELECT
    Attrition,
    COUNT(*) AS Total_Employees,
    ROUND(AVG(Salary), 2) AS Average_Salary,
    MIN(Salary) AS Minimum_Salary,
    MAX(Salary) AS Maximum_Salary
FROM employees
GROUP BY Attrition;
"""

salary_by_attrition = pd.read_sql_query(query, connection)

salary_by_attrition

  Attrition  Total_Employees  Average_Salary  Minimum_Salary  Maximum_Salary
0        No              882       128396.05         40039.0      352095.375
1       Yes              118       124779.04         41732.0      236298.000

## Average Experience by Attrition Status

We will compare employee experience between employees who stayed and employees who left.

This can help identify whether attrition is concentrated among less-experienced or more-experienced employees.

In [33]:
query = """
SELECT
    Attrition,
    COUNT(*) AS Total_Employees,
    ROUND(AVG(Experience), 2) AS Average_Experience,
    MIN(Experience) AS Minimum_Experience,
    MAX(Experience) AS Maximum_Experience
FROM employees
GROUP BY Attrition;
"""

experience_by_attrition = pd.read_sql_query(query, connection)

experience_by_attrition

,Attrition,Total_Employees,Average_Experience,Minimum_Experience,Maximum_Experience
0,No,882,9.78,0,38
1,Yes,118,9.87,0,36

## Average Job Satisfaction by Attrition Status

Job satisfaction is an important employee-retention indicator.

We will compare average job satisfaction between employees who stayed and employees who left.

In [ ]:
query = """
SELECT
    Attrition,
    COUNT(*) AS Total_Employees,
    ROUND(AVG(Job_Satisfaction), 2) AS Average_Job_Satisfaction,
    MIN(Job_Satisfaction) AS Minimum_Satisfaction,
    MAX(Job_Satisfaction) AS Maximum_Satisfaction
FROM employees
GROUP BY Attrition;
"""

satisfaction_by_attrition = pd.read_sql_query(query, connection)

satisfaction_by_attrition

,Attrition,Total_Employees,Average_Job_Satisfaction,Minimum_Satisfaction,Maximum_Satisfaction
0,No,882,7.17,3.0,10.0
1,Yes,118,3.58,3.0,7.0

## Average Performance Score by Attrition

We will compare the average performance score of employees who stayed and employees who left.

This allows us to investigate whether attrition patterns differ across performance levels.

In [35]:
query = """
SELECT
    Attrition,
    COUNT(*) AS Total_Employees,
    ROUND(AVG(Performance_Score), 2) AS Average_Performance_Score,
    MIN(Performance_Score) AS Minimum_Performance_Score,
    MAX(Performance_Score) AS Maximum_Performance_Score
FROM employees
GROUP BY Attrition;
"""

performance_by_attrition = pd.read_sql_query(query, connection)

performance_by_attrition

,Attrition,Total_Employees,Average_Performance_Score,Minimum_Performance_Score,Maximum_Performance_Score
0,No,882,3.00,1,5
1,Yes,118,3.03,1,5

## Average Manager Rating by Attrition

Manager rating may provide insight into the relationship between management experience and employee retention.

We will compare average manager ratings between employees who stayed and employees who left.

In [36]:
query = """
SELECT
    Attrition,
    COUNT(*) AS Total_Employees,
    ROUND(AVG(Manager_Rating), 2) AS Average_Manager_Rating
FROM employees
GROUP BY Attrition;
"""

manager_rating_by_attrition = pd.read_sql_query(query, connection)

manager_rating_by_attrition

  Attrition  Total_Employees  Average_Manager_Rating
0        No              882                    7.03
1       Yes              118                    7.03

## Average Work Hours by Attrition

We will compare average weekly work hours between employees who stayed and employees who left.

This allows us to investigate whether workload differs between the two groups.

In [37]:
query = """
SELECT
    Attrition,
    COUNT(*) AS Total_Employees,
    ROUND(AVG(Work_Hours), 2) AS Average_Work_Hours,
    MIN(Work_Hours) AS Minimum_Work_Hours,
    MAX(Work_Hours) AS Maximum_Work_Hours
FROM employees
GROUP BY Attrition;
"""

work_hours_by_attrition = pd.read_sql_query(query, connection)

work_hours_by_attrition

,Attrition,Total_Employees,Average_Work_Hours,Minimum_Work_Hours,Maximum_Work_Hours
0,No,882,44.83,35,55
1,Yes,118,44.57,35,55

## Attrition by Department and Overtime

We will now perform a multi-dimensional analysis.

Instead of grouping employees by only one variable, we will group them by:

- Department
- Overtime

This allows us to investigate whether overtime-related attrition differs across departments.

In [38]:
query = """
SELECT
    Department,
    Overtime,
    COUNT(*) AS Total_Employees,

    SUM(
        CASE
            WHEN Attrition = 'Yes' THEN 1
            ELSE 0
        END
    ) AS Employees_Left,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN Attrition = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS Attrition_Rate

FROM employees

GROUP BY
    Department,
    Overtime

ORDER BY
    Department,
    Attrition_Rate DESC;
"""

department_overtime_attrition = pd.read_sql_query(query, connection)

department_overtime_attrition

  Department Overtime  Total_Employees  Employees_Left  Attrition_Rate
0    Finance      Yes               90              17           18.89
1    Finance       No              104               0            0.00
2         HR      Yes              102              24           23.53
3         HR       No              127               0            0.00
4         IT      Yes               97              23           23.71
5         IT       No               85               0            0.00
6  Marketing      Yes              107              29           27.10
7  Marketing       No               89               0            0.00
8      Sales      Yes               94              25           26.60
9      Sales       No              105               0            0.00

## Attrition by Job Satisfaction Level

We will calculate employee attrition for each job satisfaction level.

This allows us to determine whether lower or higher satisfaction groups have different attrition rates.

In [39]:
query = """
SELECT
    Job_Satisfaction,
    COUNT(*) AS Total_Employees,

    SUM(
        CASE
            WHEN Attrition = 'Yes' THEN 1
            ELSE 0
        END
    ) AS Employees_Left,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN Attrition = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS Attrition_Rate

FROM employees

GROUP BY Job_Satisfaction

ORDER BY Job_Satisfaction;
"""

satisfaction_attrition = pd.read_sql_query(query, connection)

satisfaction_attrition

   Job_Satisfaction  Total_Employees  Employees_Left  Attrition_Rate
0               3.0               76              62           81.58
1               4.0               85              52           61.18
2               5.0               86               0            0.00
3               6.0              176               0            0.00
4               7.0              214               4            1.87
5               8.0              168               0            0.00
6               9.0              101               0            0.00
7              10.0               94               0            0.00

## Departments with High Attrition

The `HAVING` clause is used to filter grouped results.

We will identify departments where the attrition rate is greater than 12%.

In [ ]:
query = """
SELECT
    Department,
    COUNT(*) AS Total_Employees,

    SUM(
        CASE
            WHEN Attrition = 'Yes' THEN 1
            ELSE 0
        END
    ) AS Employees_Left,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN Attrition = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS Attrition_Rate

FROM employees

GROUP BY Department

HAVING Attrition_Rate > 12

ORDER BY Attrition_Rate DESC;
"""

high_attrition_departments = pd.read_sql_query(query, connection)

high_attrition_departments

  Department  Total_Employees  Employees_Left  Attrition_Rate
0  Marketing              196              29           14.80
1         IT              182              23           12.64
2      Sales              199              25           12.56

## Departments with More Than 100 Employees

We will use `HAVING` with `COUNT()` to identify departments containing more than 100 employees.

In [ ]:
query = """
SELECT
    Department,
    COUNT(*) AS Total_Employees,
    ROUND(AVG(Salary), 2) AS Average_Salary
FROM employees
GROUP BY Department
HAVING COUNT(*) > 100
ORDER BY Total_Employees DESC;
"""

large_departments = pd.read_sql_query(query, connection)

large_departments

  Department  Total_Employees  Average_Salary
0         HR              229       127708.98
1      Sales              199       121986.39
2  Marketing              196       128487.83
3    Finance              194       133855.96
4         IT              182       128005.05

## Employees with High Salary and Attrition

We will identify employees who left the organization and had salaries above 150,000.

This demonstrates how multiple conditions can be combined using `WHERE`.

In [42]:
query = """
SELECT
    Employee_ID,
    Department,
    Job_Role,
    Experience,
    Salary,
    Attrition
FROM employees
WHERE Attrition = 'Yes'
  AND Salary > 150000
ORDER BY Salary DESC;
"""

high_salary_attrition = pd.read_sql_query(query, connection)

high_salary_attrition.head(20)

,Employee_ID,Department,Job_Role,Experience,Salary,Attrition
0,482,Sales,Sales Manager,14,236298.0,Yes
1,385,HR,Recruiter,17,234048.0,Yes
2,766,HR,Recruiter,16,232720.0,Yes
3,774,Sales,Sales Manager,16,229289.0,Yes
4,472,Finance,Financial Analyst,31,227554.0,Yes
5,499,HR,HR Executive,26,225588.0,Yes
6,64,Sales,Sales Executive,12,224647.0,Yes
7,620,IT,DevOps Engineer,11,222331.0,Yes
8,921,Marketing,Marketing Specialist,29,219296.0,Yes
9,136,HR,Recruiter,11,215006.0,Yes
10,825,Marketing,Marketing Specialist,18,214316.0,Yes
11,794,Marketing,SEO Executive,28,214261.0,Yes
12,541,Marketing,Marketing Specialist,12,212506.0,Yes
13,655,Sales,Sales Executive,34,211928.0,Yes
14,461,HR,HR Executive,36,209630.0,Yes
15,605,Marketing,Marketing Specialist,33,208688.0,Yes
16,902,HR,Recruiter,23,205311.0,Yes
17,188,IT,Software Engineer,12,202455.0,Yes
18,329,Sales,Sales Executive,12,202321.0,Yes
19,584,Marketing,Marketing Specialist,19,200123.0,Yes

## Employees with High Workload

We will identify employees who work more than 45 hours per week and determine their attrition status.

This can help investigate the relationship between workload and employee turnover.

In [43]:
query = """
SELECT
    Employee_ID,
    Department,
    Job_Role,
    Work_Hours,
    Overtime,
    Attrition
FROM employees
WHERE Work_Hours > 45
ORDER BY Work_Hours DESC;
"""

high_workload_employees = pd.read_sql_query(query, connection)

high_workload_employees.head(20)

,Employee_ID,Department,Job_Role,Work_Hours,Overtime,Attrition
0,7,HR,HR Executive,55,Yes,Yes
1,19,Finance,Accountant,55,No,No
2,20,Marketing,SEO Executive,55,Yes,No
3,27,HR,Data Analyst,55,No,No
4,33,Marketing,SEO Executive,55,Yes,No
5,47,Marketing,Marketing Specialist,55,No,No
6,53,Marketing,Marketing Specialist,55,Yes,No
7,75,HR,Recruiter,55,No,No
8,88,HR,Recruiter,55,No,No
9,93,Finance,Accountant,55,No,No
10,104,Sales,Sales Executive,55,No,No
11,153,HR,HR Executive,55,Yes,No
12,169,HR,Recruiter,55,No,No
13,170,Sales,Sales Executive,55,No,No
14,178,Finance,Accountant,55,No,No
15,183,Sales,Sales Executive,55,Yes,Yes
16,190,HR,HR Executive,55,No,No
17,209,Sales,Sales Executive,55,No,No
18,276,HR,Recruiter,55,No,No
19,287,IT,DevOps Engineer,55,No,No

## Final SQL Analysis Summary

We will create a summary table containing key organizational metrics.

The metrics include:

- Total employees
- Employees who left
- Average salary
- Average experience
- Average job satisfaction
- Overall attrition rate

In [ ]:
query = """
SELECT
    COUNT(*) AS Total_Employees,

    SUM(
        CASE
            WHEN Attrition = 'Yes' THEN 1
            ELSE 0
        END
    ) AS Employees_Left,

    ROUND(AVG(Salary), 2) AS Average_Salary,

    ROUND(AVG(Experience), 2) AS Average_Experience,

    ROUND(AVG(Job_Satisfaction), 2) AS Average_Job_Satisfaction,

    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN Attrition = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS Attrition_Rate

FROM employees;
"""

sql_summary = pd.read_sql_query(query, connection)

sql_summary

,Total_Employees,Employees_Left,Average_Salary,Average_Experience,Average_Job_Satisfaction,Attrition_Rate
0,1000,118,127969.24,9.79,6.75,11.8

## Export SQL Summary

The final SQL summary will be saved to the processed data directory for future reporting and documentation.

In [45]:
sql_summary.to_csv("../data/processed/sql_summary.csv", index=False)

print("SQL summary saved successfully.")

SQL summary saved successfully.

## Close the Database Connection

The SQL analysis is complete, so we will close the SQLite database connection.

In [46]:
connection.close()

print("SQLite database connection closed successfully.")

SQLite database connection closed successfully.